### ISSUE TITLE
Lost connection to MySQL server at 'handshake: reading inital communication packet', system error: 35

### ISSUE THREAD

**Issue by renhaizhou** [pingcap/tidb-docker-compose#81]
mysql -h 127.0.0.1 -P 4000 -u root
ERROR 2013 (HY000): Lost connection to MySQL server at 'handshake: reading inital communication packet', system error: 35

macos

**Comment by tennix** [comment]
@renhaizhou What did you do to the cluster?

**Comment by renhaizhou** [comment]
did nothing

**Comment by renhaizhou** [comment]
tidb_1            |     runtime/debug/stack.go:16 +0x22
tidb_1            | github.com/pingcap/tidb/session.mustExecute(0x26f75c0, 0xc000902700, 0x2420270, 0xc6)
tidb_1            |     github.com/pingcap/tidb@/session/bootstrap.go:995 +0xac
tidb_1            | github.com/pingcap/tidb/session.doDMLWorks(0x26f75c0, 0xc000902700)
tidb_1            |     github.com/pingcap/tidb@/session/bootstrap.go:949 +0x98
tidb_1            | github.com/pingcap/tidb/session.bootstrap(0x26f75c0, 0xc000902700)
tidb_1            |     github.com/pingcap/tidb@/session/bootstrap.go:296 +0x359
tidb_1            | github.com/pingcap/tidb/session.runInBootstrapSession(0x26c7bc0, 0xc0004520f0, 0x244c2f0)
tidb_1            |     github.com/pingcap/tidb@/session/session.go:1661 +0x266
tidb_1            | github.com/pingcap/tidb/session.BootstrapSession(0x26c7bc0, 0xc0004520f0, 0x0, 0x0, 0x0)
tidb_1            |     github.com/pingcap/tidb@/session/session.go:1575 +0x769
tidb_1            | main.createStoreAndDomain()
tidb_1            |     github.com/pingcap/tidb@/tidb-server/main.go:238 +0x157
tidb_1            | main.main()
tidb_1            |     github.com/pingcap/tidb@/tidb-server/main.go:176 +0x1b5
tidb_1            | goroutine 1 [running]:
tidb_1            | runtime/debug.Stack(0x11e1a300, 0x0, 0x1)
tidb_1            |     runtime/debug/stack.go:24 +0x9d
tidb_1            | runtime/debug.PrintStack()
tidb_1            |     runtime/debug/stack.go:16 +0x22
tidb_1            | github.com/pingcap/tidb/session.mustExecute(0x26f75c0, 0xc00090a400, 0x2420270, 0xc6)
tidb_1            |     github.com/pingcap/tidb@/session/bootstrap.go:995 +0xac
tidb_1            | github.com/pingcap/tidb/session.doDMLWorks(0x26f75c0, 0xc00090a400)
tidb_1            |     github.com/pingcap/tidb@/session/bootstrap.go:949 +0x98
tidb_1            | github.com/pingcap/tidb/session.bootstrap(0x26f75c0, 0xc00090a400)
tidb_1            |     github.com/pingcap/tidb@/session/bootstrap.go:296 +0x359
tidb_1            | github.com/pingcap/tidb/session.runInBootstrapSession(0x26c7bc0, 0xc0004f0960, 0x244c2f0)
tidb_1            |     github.com/pingcap/tidb@/session/session.go:1661 +0x266
tidb_1            | github.com/pingcap/tidb/session.BootstrapSession(0x26c7bc0, 0xc0004f0960, 0x0, 0x0, 0x0)
tidb_1            |     github.com/pingcap/tidb@/session/session.go:1575 +0x769
tidb_1            | main.createStoreAndDomain()
tidb_1            |     github.com/pingcap/tidb@/tidb-server/main.go:238 +0x157
tidb_1            | main.main()
tidb_1            |     github.com/pingcap/tidb@/tidb-server/main.go:176 +0x1b5

**Comment by renhaizhou** [comment]
docker-compose logs tikv0
Attaching to tidb-docker-compose_tikv0_1

**Comment by tennix** [comment]
Are all components running? You can verify this by `docker-compose ps`.
*Note:* The logs are in the logs directory, so you cannot see logs by `docker-compose logs` or `docker logs`.

**Comment by renhaizhou** [comment]
docker-compose ps
tidb-docker-compose_grafana_1          /run.sh                          Up      0.0.0.0:3000->3000/tcp                           
tidb-docker-compose_pd0_1              /pd-server --name=pd0 --cl ...   Up      0.0.0.0:32769->2379/tcp, 2380/tcp                
tidb-docker-compose_pd1_1              /pd-server --name=pd1 --cl ...   Up      0.0.0.0:32770->2379/tcp, 2380/tcp                
tidb-docker-compose_pd2_1              /pd-server --name=pd2 --cl ...   Up      0.0.0.0:32768->2379/tcp, 2380/tcp                
tidb-docker-compose_prometheus_1       /bin/prometheus --log.leve ...   Up      0.0.0.0:9090->9090/tcp                           
tidb-docker-compose_pushgateway_1      /bin/pushgateway --log.lev ...   Up      9091/tcp                                         
tidb-docker-compose_tidb-vision_1      /bin/sh -c sed -i -e "s/PD ...   Up      2015/tcp, 443/tcp, 80/tcp, 0.0.0.0:8010->8010/tcp
tidb-docker-compose_tidb_1             /tidb-server --store=tikv  ...   Up      0.0.0.0:10080->10080/tcp, 0.0.0.0:4000->4000/tcp 
tidb-docker-compose_tikv0_1            /tikv-server --addr=0.0.0. ...   Up      20160/tcp                                        
tidb-docker-compose_tikv1_1            /tikv-server --addr=0.0.0. ...   Up      20160/tcp                                        
tidb-docker-compose_tikv2_1            /tikv-server --addr=0.0.0. ...   Up      20160/tcp                                        
tidb-docker-compose_tispark-master_1   /opt/spark/sbin/start-mast ...   Up      0.0.0.0:7077->7077/tcp, 0.0.0.0:8080->8080/tcp   
tidb-docker-compose_tispark-slave0_1   /opt/spark/sbin/start-slav ...   Up      0.0.0.0:38081->38081/tcp

**Comment by renhaizhou** [comment]
tidb_1            |     github.com/pingcap/tidb@/session/bootstrap.go:995 +0xac
tidb_1            | github.com/pingcap/tidb/session.doDMLWorks(0x26f75c0, 0xc0003c2100)
tidb_1            |     github.com/pingcap/tidb@/session/bootstrap.go:949 +0x98
tidb_1            | github.com/pingcap/tidb/session.bootstrap(0x26f75c0, 0xc0003c2100)
tidb_1            |     github.com/pingcap/tidb@/session/bootstrap.go:296 +0x359
tidb_1            | github.com/pingcap/tidb/session.runInBootstrapSession(0x26c7bc0, 0xc0004ef2c0, 0x244c2f0)
tidb_1            |     github.com/pingcap/tidb@/session/session.go:1661 +0x266
tidb_1            | github.com/pingcap/tidb/session.BootstrapSession(0x26c7bc0, 0xc0004ef2c0, 0x0, 0x0, 0x0)
tidb_1            |     github.com/pingcap/tidb@/session/session.go:1575 +0x769
tidb_1            | main.createStoreAndDomain()
tidb_1            |     github.com/pingcap/tidb@/tidb-server/main.go:238 +0x157
tidb_1            | main.main()
tidb_1            |     github.com/pingcap/tidb@/tidb-server/main.go:176 +0x1b5
pd0_1             | {"level":"warn","ts":"2019-11-08T06:09:14.832Z","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-b706d2fa-eab8-47d5-ab0e-f375a4e5b2f8/pd0:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
pd2_1             | {"level":"warn","ts":"2019-11-08T06:09:16.688Z","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-41b2bd66-5c91-4df1-af1d-9971a070433e/pd2:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
pd1_1             | {"level":"warn","ts":"2019-11-08T06:09:21.862Z","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-131ac0b7-4d29-420c-b5d7-0297634a5a8f/pd1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
pd1_1             | {"level":"warn","ts":"2019-11-08T06:10:04.956Z","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-131ac0b7-4d29-420c-b5d7-0297634a5a8f/pd1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
pd1_1             | {"level":"warn","ts":"2019-11-08T06:09:46.011Z","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-131ac0b7-4d29-420c-b5d7-0297634a5a8f/pd1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
pd1_1             | {"level":"warn","ts":"2019-11-08T06:10:06.251Z","caller":"clientv3/retry_interceptor.go:60","msg":"retrying of unary invoker failed","target":"endpoint://client-131ac0b7-4d29-420c-b5d7-0297634a5a8f/pd1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

**Comment by renhaizhou** [comment]
pd0.log
[2019/11/08 07:38:59.344 +00:00] [ERROR] [metricutil.go:70] ["could not push metrics to Prometheus Pushgateway"] [error="Put http://pushgateway:9091/metrics/job/pd0/instance/c8771896f7be: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:39:03.451 +00:00] [ERROR] [client.go:110] ["region sync with leader meet error"] [error="rpc error: code = Unknown desc = TiKV cluster not bootstrapped, please start TiKV first"]
[2019/11/08 07:39:14.364 +00:00] [ERROR] [metricutil.go:70] ["could not push metrics to Prometheus Pushgateway"] [error="Put http://pushgateway:9091/metrics/job/pd0/instance/c8771896f7be: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:39:29.374 +00:00] [ERROR] [metricutil.go:70] ["could not push metrics to Prometheus Pushgateway"] [error="Put http://pushgateway:9091/metrics/job/pd0/instance/c8771896f7be: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:39:44.384 +00:00] [ERROR] [metricutil.go:70] ["could not push metrics to Prometheus Pushgateway"] [error="Put http://pushgateway:9091/metrics/job/pd0/instance/c8771896f7be: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:39:59.392 +00:00] [ERROR] [metricutil.go:70] ["could not push metrics to Prometheus Pushgateway"] [error="Put http://pushgateway:9091/metrics/job/pd0/instance/c8771896f7be: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:40:14.400 +00:00] [ERROR] [metricutil.go:70] ["could not push metrics to Prometheus Pushgateway"] [error="Put http://pushgateway:9091/metrics/job/pd0/instance/c8771896f7be: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:40:22.174 +00:00] [ERROR] [client.go:110] ["region sync with leader meet error"] [error="rpc error: code = Canceled desc = context canceled"]
[2019/11/08 07:40:23.185 +00:00] [ERROR] [tso.go:126] ["system time may be incorrect"] [last=2019/11/08 07:40:24.451 +00:00] [next=2019/11/08 07:40:23.185 +00:00]
[2019/11/08 07:40:29.409 +00:00] [ERROR] [metricutil.go:70] ["could not push metrics to Prometheus Pushgateway"] [error="Put http://pushgateway:9091/metrics/job/pd0/instance/c8771896f7be: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
=============================================
tidb.log
[2019/11/08 07:39:01.373 +00:00] [INFO] [printer.go:40] ["Welcome to TiDB."] ["Release Version"=v4.0.0-alpha-760-ga7854936b] ["Git Commit Hash"=a7854936bf6771f1716b11ab11775672de2e143c] ["Git Branch"=master] ["UTC Build Time"="2019-11-07 12:08:54"] [GoVersion="go version go1.13 linux/amd64"] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]
[2019/11/08 07:39:01.377 +00:00] [INFO] [printer.go:53] ["loaded config"] [config="{\"host\":\"0.0.0.0\",\"advertise-address\":\"\",\"port\":4000,\"cors\":\"\",\"store\":\"tikv\",\"path\":\"pd0:2379,pd1:2379,pd2:2379\",\"socket\":\"\",\"lease\":\"0\",\"run-ddl\":true,\"split-table\":true,\"token-limit\":1000,\"oom-use-tmp-storage\":true,\"oom-action\":\"log\",\"mem-quota-query\":34359738368,\"enable-streaming\":false,\"enable-batch-dml\":false,\"txn-local-latches\":{\"enabled\":false,\"capacity\":2048000},\"lower-case-table-names\":2,\"log\":{\"level\":\"error\",\"format\":\"text\",\"disable-timestamp\":false,\"enable-timestamp\":null,\"disable-error-stack\":null,\"enable-error-stack\":null,\"file\":{\"filename\":\"/logs/tidb.log\",\"max-size\":300,\"max-days\":0,\"max-backups\":0},\"slow-query-file\":\"\",\"slow-threshold\":300,\"expensive-threshold\":10000,\"query-log-max-len\":2048,\"record-plan-in-slow-log\":1},\"security\":{\"skip-grant-table\":false,\"ssl-ca\":\"\",\"ssl-cert\":\"\",\"ssl-key\":\"\",\"cluster-ssl-ca\":\"\",\"cluster-ssl-cert\":\"\",\"cluster-ssl-key\":\"\"},\"status\":{\"status-host\":\"0.0.0.0\",\"metrics-addr\":\"pushgateway:9091\",\"status-port\":10080,\"metrics-interval\":15,\"report-status\":true,\"record-db-qps\":false},\"performance\":{\"max-procs\":0,\"max-memory\":0,\"stats-lease\":\"3s\",\"stmt-count-limit\":5000,\"feedback-probability\":0,\"query-feedback-limit\":1024,\"pseudo-estimate-ratio\":0.7,\"force-priority\":\"NO_PRIORITY\",\"bind-info-lease\":\"3s\",\"txn-total-size-limit\":104857600,\"tcp-keep-alive\":true,\"cross-join\":true,\"run-auto-analyze\":true},\"prepared-plan-cache\":{\"enabled\":false,\"capacity\":100,\"memory-guard-ratio\":0.1},\"opentracing\":{\"enable\":false,\"rpc-metrics\":false,\"sampler\":{\"type\":\"const\",\"param\":1,\"sampling-server-url\":\"\",\"max-operations\":0,\"sampling-refresh-interval\":0},\"reporter\":{\"queue-size\":0,\"buffer-flush-interval\":0,\"log-spans\":false,\"local-agent-host-port\":\"\"}},\"proxy-protocol\":{\"networks\":\"\",\"header-timeout\":5},\"tikv-client\":{\"grpc-connection-count\":16,\"grpc-keepalive-time\":10,\"grpc-keepalive-timeout\":3,\"commit-timeout\":\"41s\",\"max-batch-size\":128,\"overload-threshold\":200,\"max-batch-wait-time\":0,\"batch-wait-size\":8,\"enable-chunk-rpc\":true,\"region-cache-ttl\":600},\"binlog\":{\"enable\":false,\"ignore-error\":false,\"write-timeout\":\"15s\",\"binlog-socket\":\"\",\"strategy\":\"range\"},\"compatible-kill-query\":false,\"plugin\":{\"dir\":\"\",\"load\":\"\"},\"pessimistic-txn\":{\"enable\":true,\"max-retry-count\":256},\"check-mb4-value-in-utf8\":true,\"treat-old-version-utf8-as-utf8mb4\":true,\"enable-table-lock\":false,\"delay-clean-table-lock\":0,\"split-region-max-num\":1000,\"stmt-summary\":{\"max-stmt-count\":100,\"max-sql-length\":4096}}"]
[2019/11/08 07:39:01.402 +00:00] [ERROR] [main.go:300] ["could not push metrics to prometheus pushgateway"] [err="Put http://pushgateway:9091/metrics/job/tidb/instance/126af1544bba_4000: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:39:03.417 +00:00] [ERROR] [client.go:200] ["[pd] failed to get cluster id"] [error="rpc error: code = Unknown desc = server not started"]
[2019/11/08 07:39:03.425 +00:00] [ERROR] [client.go:200] ["[pd] failed to get cluster id"] [error="rpc error: code = Unknown desc = server not started"]
[2019/11/08 07:39:03.430 +00:00] [ERROR] [client.go:200] ["[pd] failed to get cluster id"] [error="rpc error: code = Unknown desc = server not started"]
[2019/11/08 07:39:16.414 +00:00] [ERROR] [main.go:300] ["could not push metrics to prometheus pushgateway"] [err="Put http://pushgateway:9091/metrics/job/tidb/instance/126af1544bba_4000: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:39:31.423 +00:00] [ERROR] [main.go:300] ["could not push metrics to prometheus pushgateway"] [err="Put http://pushgateway:9091/metrics/job/tidb/instance/126af1544bba_4000: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:39:46.430 +00:00] [ERROR] [main.go:300] ["could not push metrics to prometheus pushgateway"] [err="Put http://pushgateway:9091/metrics/job/tidb/instance/126af1544bba_4000: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:40:01.436 +00:00] [ERROR] [main.go:300] ["could not push metrics to prometheus pushgateway"] [err="Put http://pushgateway:9091/metrics/job/tidb/instance/126af1544bba_4000: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:40:16.442 +00:00] [ERROR] [main.go:300] ["could not push metrics to prometheus pushgateway"] [err="Put http://pushgateway:9091/metrics/job/tidb/instance/126af1544bba_4000: dial tcp: lookup pushgateway on 127.0.0.11:53: no such host"]
[2019/11/08 07:40:58.657 +00:00] [INFO] [printer.go:40] ["Welcome to TiDB."] ["Release Version"=v4.0.0-alpha-760-ga7854936b] ["Git Commit Hash"=a7854936bf6771f1716b11ab11775672de2e143c] ["Git Branch"=master] ["UTC Build Time"="2019-11-07 12:08:54"] [GoVersion="go version go1.13 linux/amd64"] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]
[2019/11/08 07:40:58.659 +00:00] [INFO] [printer.go:53] ["loaded config"] [config="{\"host\":\"0.0.0.0\",\"advertise-address\":\"\",\"port\":4000,\"cors\":\"\",\"store\":\"tikv\",\"path\":\"pd0:2379,pd1:2379,pd2:2379\",\"socket\":\"\",\"lease\":\"0\",\"run-ddl\":true,\"split-table\":true,\"token-limit\":1000,\"oom-use-tmp-storage\":true,\"oom-action\":\"log\",\"mem-quota-query\":34359738368,\"enable-streaming\":false,\"enable-batch-dml\":false,\"txn-local-latches\":{\"enabled\":false,\"capacity\":2048000},\"lower-case-table-names\":2,\"log\":{\"level\":\"error\",\"format\":\"text\",\"disable-timestamp\":false,\"enable-timestamp\":null,\"disable-error-stack\":null,\"enable-error-stack\":null,\"file\":{\"filename\":\"/logs/tidb.log\",\"max-size\":300,\"max-days\":0,\"max-backups\":0},\"slow-query-file\":\"\",\"slow-threshold\":300,\"expensive-threshold\":10000,\"query-log-max-len\":2048,\"record-plan-in-slow-log\":1},\"security\":{\"skip-grant-table\":false,\"ssl-ca\":\"\",\"ssl-cert\":\"\",\"ssl-key\":\"\",\"cluster-ssl-ca\":\"\",\"cluster-ssl-cert\":\"\",\"cluster-ssl-key\":\"\"},\"status\":{\"status-host\":\"0.0.0.0\",\"metrics-addr\":\"pushgateway:9091\",\"status-port\":10080,\"metrics-interval\":15,\"report-status\":true,\"record-db-qps\":false},\"performance\":{\"max-procs\":0,\"max-memory\":0,\"stats-lease\":\"3s\",\"stmt-count-limit\":5000,\"feedback-probability\":0,\"query-feedback-limit\":1024,\"pseudo-estimate-ratio\":0.7,\"force-priority\":\"NO_PRIORITY\",\"bind-info-lease\":\"3s\",\"txn-total-size-limit\":104857600,\"tcp-keep-alive\":true,\"cross-join\":true,\"run-auto-analyze\":true},\"prepared-plan-cache\":{\"enabled\":false,\"capacity\":100,\"memory-guard-ratio\":0.1},\"opentracing\":{\"enable\":false,\"rpc-metrics\":false,\"sampler\":{\"type\":\"const\",\"param\":1,\"sampling-server-url\":\"\",\"max-operations\":0,\"sampling-refresh-interval\":0},\"reporter\":{\"queue-size\":0,\"buffer-flush-interval\":0,\"log-spans\":false,\"local-agent-host-port\":\"\"}},\"proxy-protocol\":{\"networks\":\"\",\"header-timeout\":5},\"tikv-client\":{\"grpc-connection-count\":16,\"grpc-keepalive-time\":10,\"grpc-keepalive-timeout\":3,\"commit-timeout\":\"41s\",\"max-batch-size\":128,\"overload-threshold\":200,\"max-batch-wait-time\":0,\"batch-wait-size\":8,\"enable-chunk-rpc\":true,\"region-cache-ttl\":600},\"binlog\":{\"enable\":false,\"ignore-error\":false,\"write-timeout\":\"15s\",\"binlog-socket\":\"\",\"strategy\":\"range\"},\"compatible-kill-query\":false,\"plugin\":{\"dir\":\"\",\"load\":\"\"},\"pessimistic-txn\":{\"enable\":true,\"max-retry-count\":256},\"check-mb4-value-in-utf8\":true,\"treat-old-version-utf8-as-utf8mb4\":true,\"enable-table-lock\":false,\"delay-clean-table-lock\":0,\"split-region-max-num\":1000,\"stmt-summary\":{\"max-stmt-count\":100,\"max-sql-length\":4096}}"]
[2019/11/08 07:40:59.062 +00:00] [ERROR] [client.go:200] ["[pd] failed to get cluster id"] [error="rpc error: code = Unknown desc = server not started"]
[2019/11/08 07:40:59.070 +00:00] [ERROR] [client.go:200] ["[pd] failed to get cluster id"] [error="rpc error: code = Unknown desc = server not started"]
[2019/11/08 07:40:59.074 +00:00] [ERROR] [client.go:200] ["[pd] failed to get cluster id"] [error="rpc error: code = Unknown desc = server not started"]
===================================================
tikv0.log
[2019/11/08 07:39:04.178 +00:00] [ERROR] [util.rs:326] ["request failed"] [err="Grpc(RpcFailure(RpcStatus { status: RpcStatusCode(2), details: Some(\"cluster 6756837154912198427 already bootstrapped\") }))"]
[2019/11/08 07:39:04.337 +00:00] [ERROR] [mod.rs:51] ["fail to push metrics"] [err="Msg(\"http://pushgateway:9091/metrics/job/tikv_3/instance/9725611b2928: error trying to connect: Device or resource busy (os error 16)\")"]
[2019/11/08 07:39:19.355 +00:00] [ERROR] [mod.rs:51] ["fail to push metrics"] [err="Msg(\"http://pushgateway:9091/metrics/job/tikv_3/instance/9725611b2928: error trying to connect: Device or resource busy (os error 16)\")"]
[2019/11/08 07:39:30.275 +00:00] [ERROR] [client.rs:346] ["failed to send heartbeat"] [err="Grpc(RpcFinished(Some(RpcStatus { status: RpcStatusCode(0), details: None })))"]
[2019/11/08 07:39:30.276 +00:00] [ERROR] [util.rs:286] ["request failed, retry"] [err="Grpc(RpcFinished(Some(RpcStatus { status: RpcStatusCode(0), details: None })))"]
[2019/11/08 07:39:30.276 +00:00] [ERROR] [util.rs:286] ["request failed, retry"] [err="Other(SendError(\"...\"))"]
[2019/11/08 07:39:30.277 +00:00] [ERROR] [util.rs:286] ["request failed, retry"] [err="Other(SendError(\"...\"))"]
[2019/11/08 07:39:34.366 +00:00] [ERROR] [mod.rs:51] ["fail to push metrics"] [err="Msg(\"http://pushgateway:9091/metrics/job/tikv_3/instance/9725611b2928: error trying to connect: Device or resource busy (os error 16)\")"]
[2019/11/08 07:39:49.378 +00:00] [ERROR] [mod.rs:51] ["fail to push metrics"] [err="Msg(\"http://pushgateway:9091/metrics/job/tikv_3/instance/9725611b2928: error trying to connect: Device or resource busy (os error 16)\")"]
[2019/11/08 07:40:04.397 +00:00] [ERROR] [mod.rs:51] ["fail to push metrics"] [err="Msg(\"http://pushgateway:9091/metrics/job/tikv_3/instance/9725611b2928: error trying to connect: Device or resource busy (os error 16)\")"]
[2019/11/08 07:40:19.408 +00:00] [ERROR] [mod.rs:51] ["fail to push metrics"] [err="Msg(\"http://pushgateway:9091/metrics/job/tikv_3/instance/9725611b2928: error trying to connect: Device or resource busy (os error 16)\")"]
[2019/11/08 07:40:20.725 +00:00] [ERROR] [kv.rs:1186] ["KvService::batch_raft send response fail"] [err=RemoteStopped]
[2019/11/08 07:40:20.726 +00:00] [ERROR] [kv.rs:1186] ["KvService::batch_raft send response fail"] [err=RemoteStopped]
[2019/11/08 07:40:20.800 +00:00] [ERROR] [mod.rs:213] ["Failed to send read flow statistics"] [err="channel has been closed"]

**Comment by tennix** [comment]
@renhaizhou Sorry for the late reply, is your problem solved? How did you fix it?

**Comment by renhaizhou** [comment]
I restarted a few times and then solved it, thank you

**Comment by tennix** [comment]
Great! I guess it may because Docker runs on macOS using Linux VM, which are not as stable as run natively on Linux machine.
